from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/health/", include("apps.core.health.urls")),
    path("api/files/", include("apps.core.files.urls")),
    path("api/auth/", include("apps.accounts.urls")),
    path("api/rbac/", include("apps.rbac.urls")),
    path("api/org/", include("apps.org.urls")),
    path("api/people/", include("apps.people.urls")),
    path("api/projects/", include("apps.projects.urls")),
    path("api/communications/", include("apps.communications.urls")),
    path("api/hr/", include("apps.hr.urls")),
    path("api/volunteers/", include("apps.volunteers.urls")),
    path("api/requests/", include("apps.requests.urls")),
    path("api/inventory/", include("apps.inventory.urls")),
    path("api/assets/", include("apps.assets.urls")),
    path("api/fleet/", include("apps.fleet.urls")),
    path("api/procurement/", include("apps.procurement.urls")),
    path("api/documents/", include("apps.documents.urls")),
    path("api/reporting/", include("apps.reporting.urls")),
    path("api/finance/", include("apps.finance.urls")),
    path("api/budgets/", include("apps.budgets.urls")),
    path("api/memberships/", include("apps.memberships.urls")),
    path("api/alerts/", include("apps.alerts.urls")),
    path("api/shelters/", include("apps.shelters.urls")),
    path("api/case-management/", include("apps.case_management.urls")),
    path("api/health-facilities/", include("apps.health_facilities.urls")),
    path("api/patients/", include("apps.patients.urls")),
    path("api/medical/", include("apps.medical.urls")),
    path("api/epidemiology/", include("apps.epidemiology.urls")),
    path("api/events/", include("apps.events.urls")),
    path("api/missing-persons/", include("apps.missing_persons.urls")),
    path("api/victim-identification/", include("apps.victim_identification.urls")),
    path("api/locations/", include("apps.locations.urls")),
    path("api/content/", include("apps.content.urls")),
]
