# Generated by Django 6.0.4 on 2026-04-13 16:32

import re
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_code_fragment(value):
    token = re.sub(r"[^a-z0-9]+", "-", (value or "").strip().lower()).strip("-")
    return token or "sector"


def backfill_sectors_and_owners(apps, schema_editor):
    Sector = apps.get_model("cybergrc", "Sector")
    Stakeholder = apps.get_model("cybergrc", "Stakeholder")
    CriticalInfrastructure = apps.get_model("cybergrc", "CriticalInfrastructure")
    CyberStandard = apps.get_model("cybergrc", "CyberStandard")
    EmergencyResponseAsset = apps.get_model("cybergrc", "EmergencyResponseAsset")

    sector_cache = {}

    def get_sector(organization_id, raw_name):
        normalized_name = (raw_name or "").strip()
        if not normalized_name:
            return None

        cache_key = (organization_id, normalized_name.lower())
        if cache_key in sector_cache:
            return sector_cache[cache_key]

        existing = Sector.objects.filter(organization_id=organization_id, name__iexact=normalized_name).first()
        if existing:
            sector_cache[cache_key] = existing
            return existing

        base = normalize_code_fragment(normalized_name)
        code = f"sector-{organization_id}-{base}"[:80]
        suffix = 1
        while Sector.objects.filter(code=code).exists():
            suffix_token = f"-{suffix}"
            code = f"sector-{organization_id}-{base}"[: 80 - len(suffix_token)] + suffix_token
            suffix += 1

        created = Sector.objects.create(
            organization_id=organization_id,
            code=code,
            name=normalized_name,
            status="active",
        )
        sector_cache[cache_key] = created
        return created

    for stakeholder in Stakeholder.objects.exclude(sector=""):
        sector = get_sector(stakeholder.organization_id, stakeholder.sector)
        if sector and stakeholder.sector_ref_id != sector.id:
            stakeholder.sector_ref_id = sector.id
            stakeholder.save(update_fields=["sector_ref", "updated_at"])

    for infrastructure in CriticalInfrastructure.objects.exclude(sector=""):
        sector = get_sector(infrastructure.organization_id, infrastructure.sector)
        if sector and infrastructure.sector_ref_id != sector.id:
            infrastructure.sector_ref_id = sector.id
            infrastructure.save(update_fields=["sector_ref", "updated_at"])

    for standard in CyberStandard.objects.exclude(target_sector=""):
        sector = get_sector(standard.organization_id, standard.target_sector)
        if sector and standard.target_sector_ref_id != sector.id:
            standard.target_sector_ref_id = sector.id
            standard.save(update_fields=["target_sector_ref", "updated_at"])

    stakeholder_lookup = {}
    for stakeholder in Stakeholder.objects.all():
        stakeholder_lookup[(stakeholder.organization_id, (stakeholder.name or "").strip().lower())] = stakeholder.id

    for asset in EmergencyResponseAsset.objects.exclude(owner_name=""):
        match_id = stakeholder_lookup.get((asset.organization_id, (asset.owner_name or "").strip().lower()))
        if match_id and asset.owner_stakeholder_id != match_id:
            asset.owner_stakeholder_id = match_id
            asset.save(update_fields=["owner_stakeholder", "updated_at"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('cybergrc', '0002_actionplantask_capacityassessment_deskstudyreview_and_more'),
        ('org', '0003_org_types_and_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='owner_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_response_assets', to='cybergrc.stakeholder'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('active', 'Active'), ('in_review', 'In review'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cybergrc_sectors', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='criticalinfrastructure',
            name='sector_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_infrastructure', to='cybergrc.sector'),
        ),
        migrations.AddField(
            model_name='cyberstandard',
            name='target_sector_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_standards', to='cybergrc.sector'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='sector_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholders', to='cybergrc.sector'),
        ),
        migrations.RunPython(backfill_sectors_and_owners, noop_reverse),
    ]
