# Generated by Django 6.0.4 on 2026-04-16 01:09

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def migrate_existing_consultations(apps, schema_editor):
    StakeholderConsultation = apps.get_model("cybergrc", "StakeholderConsultation")
    status_map = {
        "planned": "scheduled",
        "in_progress": "confirmed",
        "active": "confirmed",
        "in_review": "confirmed",
        "submitted": "confirmed",
        "validated": "confirmed",
        "completed": "completed",
        "archived": "archived",
        "draft": "draft",
    }

    for consultation in StakeholderConsultation.objects.all().iterator():
        update_fields = []
        next_status = status_map.get(consultation.status, consultation.status or "draft")
        if consultation.status != next_status:
            consultation.status = next_status
            update_fields.append("status")

        if consultation.planned_date and not consultation.start_datetime:
            consultation.start_datetime = timezone.make_aware(datetime.combine(consultation.planned_date, time(hour=9)))
            update_fields.append("start_datetime")

        if consultation.completed_date and not consultation.end_datetime:
            consultation.end_datetime = timezone.make_aware(datetime.combine(consultation.completed_date, time(hour=11)))
            update_fields.append("end_datetime")

        if update_fields:
            consultation.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("cybergrc", "0003_emergencyresponseasset_owner_stakeholder_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="agenda",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="attendees",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="dial_in_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="engagement_channel",
            field=models.CharField(
                choices=[
                    ("in_person", "In person"),
                    ("phone", "Phone"),
                    ("video", "Video"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="follow_up_reminder_sent_for",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="meeting_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="minutes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stakeholderconsultation",
            name="start_reminder_sent_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_existing_consultations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stakeholderconsultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("rescheduled", "Rescheduled"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
