# Generated by Django 6.0.4 on 2026-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergrc', '0004_stakeholder_consultation_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='capacity_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='deployment_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('staged', 'Staged'), ('deployed', 'Deployed'), ('returning', 'Returning'), ('maintenance', 'Maintenance')], default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='last_readiness_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='mobilization_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
