# Generated by Django 6.0.4 on 2026-04-17 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergrc', '0007_assetinventoryitem_distributiongroup_and_more'),
        ('org', '0003_org_types_and_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('module_key', models.CharField(blank=True, max_length=80)),
                ('module_label', models.CharField(blank=True, max_length=120)),
                ('record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('record_title', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('report', 'Operational report'), ('brief', 'Briefing note'), ('minutes', 'Meeting minutes'), ('plan', 'Plan package'), ('standard_pack', 'Standards pack'), ('dossier', 'Final dossier'), ('template', 'Template')], default='report', max_length=30)),
                ('output_format', models.CharField(choices=[('markdown', 'Markdown'), ('text', 'Plain text'), ('json', 'JSON snapshot')], default='markdown', max_length=20)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('in_review', 'In review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='generated', max_length=30)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_label', models.CharField(blank=True, max_length=24)),
                ('generated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('generated_by_name', models.CharField(blank=True, max_length=255)),
                ('approved_by_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cybergrc_generated_documents', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('module_key', models.CharField(blank=True, max_length=80)),
                ('module_label', models.CharField(blank=True, max_length=120)),
                ('record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('record_title', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('cadence_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=30)),
                ('current_version_label', models.CharField(blank=True, max_length=24)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('scope_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_cycles', to='cybergrc.generateddocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cybergrc_review_cycles', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='approved', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('active', 'Active'), ('in_review', 'In review'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('completed', 'Completed'), ('archived', 'Archived')], default='completed', max_length=30)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('version_label', models.CharField(blank=True, max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to='cybergrc.generateddocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cybergrc_review_records', to='org.organization')),
                ('review_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to='cybergrc.reviewcycle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('module_key', models.CharField(blank=True, max_length=80)),
                ('module_label', models.CharField(blank=True, max_length=120)),
                ('record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('record_title', models.CharField(blank=True, max_length=255)),
                ('change_type', models.CharField(choices=[('generated', 'Generated'), ('review_started', 'Review started'), ('review_recorded', 'Review recorded'), ('approved', 'Approved'), ('updated', 'Updated'), ('superseded', 'Superseded'), ('reminder', 'Reminder'), ('archived', 'Archived')], default='updated', max_length=30)),
                ('version_label', models.CharField(blank=True, max_length=24)),
                ('summary', models.TextField(blank=True)),
                ('change_metadata', models.JSONField(blank=True, default=dict)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cybergrc_change_log_entries', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log_entries', to='cybergrc.generateddocument')),
                ('review_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log_entries', to='cybergrc.reviewcycle')),
                ('review_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log_entries', to='cybergrc.reviewrecord')),
            ],
            options={
                'ordering': ['-changed_on', '-id'],
            },
        ),
    ]
