# Generated by Django 6.0.4 on 2026-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergrc', '0008_generateddocument_reviewcycle_reviewrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalinfrastructure',
            name='geometry_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='geometry_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emergencyresponseasset',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='generated_file',
            field=models.FileField(blank=True, upload_to='generated_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='output_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('text', 'Plain text'), ('json', 'JSON snapshot'), ('pdf', 'PDF'), ('docx', 'DOCX')], default='markdown', max_length=20),
        ),
    ]
