# Generated by Django 6.0.4 on 2026-04-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cybergrc', '0004_stakeholder_consultation_meetings'),
        ('org', '0003_org_types_and_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('service_outage', 'Service outage'), ('malware', 'Malware'), ('data_breach', 'Data breach'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('unauthorized_access', 'Unauthorized access'), ('fraud', 'Fraud'), ('physical_intrusion', 'Physical intrusion'), ('supply_chain', 'Supply chain'), ('other', 'Other')], default='service_outage', max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('national', 'National significance')], default='medium', max_length=24)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assessing', 'Assessing'), ('active', 'Active'), ('contained', 'Contained'), ('recovering', 'Recovering'), ('closed', 'Closed')], default='reported', max_length=24)),
                ('source', models.CharField(choices=[('internal_report', 'Internal report'), ('external_report', 'External report'), ('monitoring', 'Monitoring alert'), ('threat_intelligence', 'Threat intelligence'), ('exercise', 'Exercise'), ('consultation', 'Consultation'), ('other', 'Other')], default='internal_report', max_length=40)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('operational_objective', models.TextField(blank=True)),
                ('cross_sector_impact', models.TextField(blank=True)),
                ('decision_log', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('next_update_due', models.DateTimeField(blank=True, null=True)),
                ('containment_target_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_target_at', models.DateTimeField(blank=True, null=True)),
                ('national_significance', models.BooleanField(default=False)),
                ('affected_infrastructure', models.ManyToManyField(blank=True, related_name='incidents', to='cybergrc.criticalinfrastructure')),
                ('affected_sectors', models.ManyToManyField(blank=True, related_name='incidents', to='cybergrc.sector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_incidents', to=settings.AUTH_USER_MODEL)),
                ('lead_stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='cybergrc.stakeholder')),
                ('linked_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='cybergrc.contingencyplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role_in_response', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('acknowledged', 'Acknowledged'), ('active', 'Active'), ('released', 'Released')], default='assigned', max_length=24)),
                ('assigned_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incident_management.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignments', to='org.organization')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_assignments', to='cybergrc.stakeholder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('attachment_type', models.CharField(choices=[('log', 'Log'), ('report', 'Report'), ('screenshot', 'Screenshot'), ('evidence', 'Evidence'), ('bulletin', 'Bulletin'), ('other', 'Other')], default='evidence', max_length=24)),
                ('reference_url', models.URLField(blank=True)),
                ('reference_label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incident_management.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_attachments', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=24)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('video', 'Video'), ('sms', 'SMS'), ('briefing', 'Briefing'), ('bulletin', 'Bulletin'), ('other', 'Other')], default='email', max_length=24)),
                ('audience', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='incident_management.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_communications', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('national', 'National significance')], default='medium', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocker_summary', models.CharField(blank=True, max_length=255)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='incident_management.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tasks', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at', 'due_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('update_type', models.CharField(choices=[('situation', 'Situation update'), ('decision', 'Decision'), ('escalation', 'Escalation'), ('containment', 'Containment'), ('recovery', 'Recovery'), ('lesson', 'Lesson learned')], default='situation', max_length=32)),
                ('message', models.TextField()),
                ('status_snapshot', models.CharField(blank=True, choices=[('reported', 'Reported'), ('assessing', 'Assessing'), ('active', 'Active'), ('contained', 'Contained'), ('recovering', 'Recovering'), ('closed', 'Closed')], max_length=24)),
                ('severity_snapshot', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('national', 'National significance')], max_length=24)),
                ('recorded_at', models.DateTimeField()),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incident_management.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_updates', to='org.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
