const DEFAULT_VIEW_LABELS = {
  list: "List",
  create: "Create",
  import: "Import",
  map: "Map",
  search: "Search",
  workflow: "Workflow",
  report: "Report",
  calendar: "Calendar",
  execute: "Execute",
};

const STAKEHOLDER_FORM_PRESENTATION = {
  variant: "editorial",
  eyebrow: "Governance & Mapping",
  sectionLabel: "Stakeholder coordination file",
  createTitle: "Create a cyber stakeholder",
  editTitle: "Update the cyber stakeholder",
  createDescription: "Fill in the identity, focal point, and engagement role used for cyber coordination.",
  editDescription: "Update the profile, primary contact, and engagement level for this cyber stakeholder.",
  footerNote: "A clear record supports coordination, consultations, and action tracking across institutions.",
  sections: [
    {
      title: "Stakeholder identity",
      description: "Define the institution and its place in the cyber governance and coordination setup.",
      fields: ["name", "stakeholder_type", "sector_ref", "status"],
    },
    {
      title: "Primary coordination contact",
      description: "Fill in the person and the channels the team should use first for operational exchanges.",
      fields: ["focal_point", "email", "phone", "engagement_role"],
    },
    {
      title: "Engagement notes",
      description: "Keep the context needed here to prepare reviews, workshops, and follow-up actions.",
      fields: ["notes"],
    },
  ],
  sidePanel: {
    title: "Build a usable stakeholder file",
    description: "This record should make it easy to understand who the stakeholder is, how to reach them, and what role they play in the cyber program.",
    keyFields: ["name", "stakeholder_type", "focal_point", "status"],
    highlights: [
      "Use the stakeholder's official name rather than an internal alias.",
      "Prioritize a named focal point and direct contact details.",
      "Write the engagement role with concrete verbs: coordinate, supervise, support, or escalate.",
    ],
  },
};

const CONSULTATION_FORM_PRESENTATION = {
  variant: "editorial",
  eyebrow: "Governance & Mapping",
  sectionLabel: "Consultation meeting file",
  createTitle: "Schedule a stakeholder consultation",
  editTitle: "Update the stakeholder consultation",
  createDescription: "Keep the meeting setup, access details, and follow-up actions in one operational file.",
  editDescription: "Update the schedule, access details, attendance notes, and follow-up actions for this consultation.",
  sections: [
    {
      title: "Meeting setup",
      description: "Define who the session is for, what format it uses, and which workflow state it is in.",
      fields: ["stakeholder", "related_infrastructure", "title", "consultation_type", "engagement_channel", "status"],
    },
    {
      title: "Timing and access",
      description: "Capture the schedule and the access path participants should use.",
      fields: ["start_datetime", "end_datetime", "meeting_location", "meeting_link", "dial_in_details", "focal_person"],
    },
    {
      title: "Agenda and attendance",
      description: "Record the objective, agenda, and who is expected to participate.",
      fields: ["objective", "agenda", "attendees"],
    },
    {
      title: "Minutes and follow-up",
      description: "Close the loop with notes, outcomes, and the next follow-up date.",
      fields: ["minutes", "outcome_summary", "follow_up_actions", "next_follow_up_date", "notes"],
    },
  ],
  sidePanel: {
    title: "Run a usable meeting record",
    description: "This file should let the team understand when the session happens, how to join it, what was decided, and what follow-up is due next.",
    keyFields: ["title", "stakeholder", "engagement_channel", "start_datetime", "status"],
    highlights: [
      "Add a direct meeting link or dial-in path for remote sessions.",
      "Keep the agenda short and action-oriented before the meeting starts.",
      "Record minutes and follow-up actions before closing the consultation.",
    ],
  },
};

function createWorkflowBlueprint(config) {
  return config;
}

const WORKFLOW_BLUEPRINTS = {
  cybergrc_stakeholders: createWorkflowBlueprint({
    objective: "Move stakeholder files from basic identification to an active coordination posture.",
    contextFields: ["stakeholder_type", "sector", "engagement_role"],
    ownerFields: ["focal_point", "email"],
    blockerRules: [
      { when: (row) => !row.focal_point, label: "Primary focal point missing" },
      { when: (row) => !row.email && !row.phone, label: "No direct contact channel" },
    ],
    stageNotes: {
      draft: "Profile not yet usable for coordination.",
      planned: "Engagement is scheduled but not active yet.",
      in_progress: "Stakeholder file is being completed for active use.",
      active: "Stakeholder is participating in coordination.",
      in_review: "Mandate or contact details are being validated.",
      submitted: "Profile has been routed for validation or approval.",
      validated: "Ready for programme use.",
      completed: "Engagement objective closed.",
      archived: "Record is kept for reference and is no longer in active use.",
    },
    nextActionLabels: {
      draft: "Complete the stakeholder profile and contact details.",
      planned: "Confirm the focal point and first engagement step.",
      active: "Keep coordination notes and responsibilities current.",
      in_review: "Validate the mandate and institutional role.",
      validated: "Use this record as the reference contact file.",
      completed: "Archive or reopen only if the engagement scope changes.",
    },
  }),
  critical_infrastructure: createWorkflowBlueprint({
    objective: "Progress infrastructure from identification to reviewed mapping with criticality and assurance context.",
    contextFields: ["sector", "essential_service", "criticality_level"],
    ownerFields: ["owner_stakeholder_name", "owner_name"],
    dueFields: ["last_assessed_at"],
    blockerRules: [
      { when: (row) => row.requires_nda && ["planned", "in_progress"].includes(row.mapping_status), label: "NDA prerequisite still open" },
      { when: (row) => ["mapped", "reviewed"].includes(row.mapping_status) && (!row.latitude || !row.longitude), label: "Coordinates missing for mapped site" },
      { when: (row) => ["high", "critical"].includes(row.criticality_level) && !row.risk_summary, label: "Risk summary missing for high criticality asset" },
    ],
    stageNotes: {
      planned: "Candidate site is queued for scoping.",
      in_progress: "Assessment and mapping are underway.",
      mapped: "Core data has been captured.",
      reviewed: "Mapping has been reviewed and can be used operationally.",
    },
    nextActionLabels: {
      planned: "Confirm scope, owner, and field assessment prerequisites.",
      in_progress: "Complete mapping data, coordinates, and assurance notes.",
      mapped: "Run the validation review with the relevant parties.",
      reviewed: "Keep coordinates and last assessment date current.",
    },
  }),
  governance_artifacts: createWorkflowBlueprint({
    objective: "Take policies, regulations, templates, and SOPs through drafting, consultation, validation, and publication.",
    contextFields: ["phase", "artifact_type", "version"],
    ownerFields: ["owner_stakeholder_name"],
    dueFields: ["next_review_date"],
    blockerRules: [
      { when: (row) => !row.summary, label: "Summary not filled in" },
      { when: (row) => ["submitted", "validated", "completed"].includes(row.status) && !row.document_reference, label: "Published reference missing" },
    ],
    nextActionLabels: {
      draft: "Finalize the core text and scope.",
      planned: "Prepare the consultation and validation path.",
      in_review: "Collect comments and consolidate revisions.",
      submitted: "Route the artifact for formal decision.",
      validated: "Publish, circulate, and schedule the review loop.",
      completed: "Maintain the current version and review cycle.",
    },
  }),
  desk_study_reviews: createWorkflowBlueprint({
    objective: "Track document analysis from intake through gap extraction and decision-ready recommendations.",
    contextFields: ["source_type", "scope", "priority"],
    ownerFields: ["document_owner", "related_stakeholder_name"],
    dueFields: ["due_date", "completed_date"],
    blockerRules: [
      { when: (row) => ["in_review", "submitted", "validated", "completed"].includes(row.status) && !row.gap_summary, label: "Gap analysis still missing" },
      { when: (row) => ["submitted", "validated", "completed"].includes(row.status) && !row.recommendation_summary, label: "Recommendations not captured" },
    ],
    nextActionLabels: {
      draft: "Capture the document source and review scope.",
      planned: "Schedule the desk review and assign the analyst.",
      in_progress: "Extract findings and critical gaps from the material.",
      in_review: "Validate the findings with the delivery lead.",
      submitted: "Convert findings into decision-ready recommendations.",
      validated: "Feed approved gaps and actions into delivery tracking.",
      completed: "Keep the review linked to action plans and updates.",
    },
  }),
  stakeholder_consultations: createWorkflowBlueprint({
    objective: "Run consultation meetings and calls with visible schedule, join details, minutes, and follow-up ownership.",
    contextFields: ["consultation_type", "engagement_channel", "stakeholder_name"],
    ownerFields: ["focal_person", "stakeholder_name"],
    dueFields: ["start_datetime", "next_follow_up_date"],
    blockerRules: [
      { when: (row) => !row.stakeholder && !row.focal_person, label: "No accountable stakeholder or focal person" },
      { when: (row) => ["scheduled", "confirmed", "rescheduled"].includes(row.status) && !row.start_datetime, label: "Meeting start time not set" },
      { when: (row) => ["video", "hybrid"].includes(row.engagement_channel) && !row.meeting_link && !row.dial_in_details, label: "Remote access details are missing" },
      { when: (row) => ["in_person", "hybrid"].includes(row.engagement_channel) && !row.meeting_location, label: "Meeting location is missing" },
      { when: (row) => row.status === "confirmed" && !row.agenda, label: "Agenda not yet captured" },
      { when: (row) => row.status === "completed" && !row.minutes && !row.outcome_summary, label: "Minutes or outcome summary still missing" },
    ],
    stageNotes: {
      draft: "The consultation exists but is not yet ready to be scheduled.",
      scheduled: "The meeting has a slot and should now be prepared for delivery.",
      confirmed: "Participants and access details are ready and the session can proceed.",
      rescheduled: "The session moved and needs updated coordination details.",
      completed: "The meeting closed and should now feed minutes and follow-up actions.",
      missed: "The planned session did not happen and needs a recovery decision.",
      archived: "The consultation record is retained for traceability only.",
    },
    nextActionLabels: {
      draft: "Clarify the purpose, target stakeholder, and preferred meeting format.",
      scheduled: "Confirm the agenda, join path, and expected attendees.",
      confirmed: "Run the session, capture minutes, and log decisions live.",
      rescheduled: "Publish the new slot and refresh the access details.",
      completed: "Track the follow-up actions and the next coordination date.",
      missed: "Decide whether to reschedule, cancel, or escalate the consultation.",
      archived: "Retain the record as reference evidence for future reviews.",
    },
  }),
  risk_register_entries: createWorkflowBlueprint({
    objective: "Take risks from identification to treatment, acceptance, or closure with a named owner and due response.",
    contextFields: ["risk_level", "category", "infrastructure_name"],
    ownerFields: ["risk_owner"],
    dueFields: ["response_deadline", "last_reviewed_at"],
    blockerRules: [
      { when: (row) => ["high", "critical"].includes(row.risk_level) && !row.response_plan, label: "Response plan missing for a priority risk" },
      { when: (row) => !row.risk_owner, label: "Risk owner not assigned" },
    ],
    stageNotes: {
      identified: "Risk has been registered but not assessed.",
      assessing: "The scenario and score are being reviewed.",
      mitigating: "Treatment actions are underway.",
      accepted: "Residual exposure was formally accepted.",
      closed: "Treatment is complete and the record can be monitored.",
    },
    nextActionLabels: {
      identified: "Confirm the owner, score, and immediate response path.",
      assessing: "Validate likelihood, impact, and treatment options.",
      mitigating: "Track delivery of the mitigation actions.",
      accepted: "Document acceptance rationale and review trigger.",
      closed: "Retain the evidence and schedule re-evaluation if needed.",
    },
  }),
  asset_inventory_items: createWorkflowBlueprint({
    objective: "Keep a usable GIS-aware inventory of critical assets, supporting systems, and dependencies that feed mapping and response planning.",
    contextFields: ["asset_type", "sector", "related_infrastructure_name"],
    ownerFields: ["owner_stakeholder_name", "owner_name"],
    blockerRules: [
      { when: (row) => !row.code, label: "Inventory code missing" },
      { when: (row) => !row.owner_stakeholder_name && !row.owner_name, label: "Owner not defined" },
      { when: (row) => ["high", "critical"].includes(row.criticality_level) && (!row.latitude || !row.longitude), label: "Coordinates missing for a critical asset" },
    ],
    nextActionLabels: {
      draft: "Define the asset identity and the system or service it supports.",
      planned: "Confirm ownership, sector, and the first mapping details.",
      active: "Keep dependencies, location, and summary current.",
      in_review: "Validate the asset record with the owning institution.",
      validated: "Use this record as an approved mapping reference.",
      completed: "Retain this asset record as an approved baseline.",
    },
  }),
  threat_events: createWorkflowBlueprint({
    objective: "Track threat activity from first signal through analysis, monitoring, mitigation, and closure.",
    contextFields: ["threat_type", "severity", "related_infrastructure_name"],
    ownerFields: ["reporting_stakeholder_name"],
    dueFields: ["first_seen_at", "last_seen_at"],
    blockerRules: [
      { when: (row) => !row.summary, label: "Threat summary missing" },
      { when: (row) => ["high", "critical"].includes(row.severity) && !row.recommended_action, label: "Recommended action missing for a serious threat" },
    ],
    stageNotes: {
      identified: "The threat signal is captured and needs triage.",
      analyzing: "The signal is being analyzed for scope and credibility.",
      monitored: "The event remains under watch and should stay updated.",
      mitigated: "Immediate action reduced the threat pressure.",
      closed: "The event is closed and kept for traceability.",
    },
    nextActionLabels: {
      identified: "Confirm the source, affected assets, and first operational note.",
      analyzing: "Clarify severity, confidence, and recommended action.",
      monitored: "Keep timestamps, locations, and linked assets current.",
      mitigated: "Document what reduced the threat and any residual watch items.",
      closed: "Retain the event as evidence and lesson input.",
    },
  }),
  vulnerability_records: createWorkflowBlueprint({
    objective: "Track vulnerabilities from discovery to remediation, acceptance, or verified closure.",
    contextFields: ["vulnerability_type", "severity", "related_infrastructure_name"],
    ownerFields: ["owner_name"],
    dueFields: ["discovered_on", "remediation_due_date"],
    blockerRules: [
      { when: (row) => !row.summary, label: "Vulnerability summary missing" },
      { when: (row) => ["high", "critical"].includes(row.severity) && !row.remediation_guidance, label: "Remediation guidance missing for a severe vulnerability" },
    ],
    stageNotes: {
      identified: "The vulnerability is logged and needs validation.",
      validating: "The weakness is being confirmed and scoped.",
      remediating: "Corrective work is in motion.",
      accepted: "Residual exposure was accepted with rationale.",
      resolved: "The vulnerability was fixed and needs closure evidence.",
      closed: "The record is closed and kept for auditability.",
    },
    nextActionLabels: {
      identified: "Confirm the weakness, owner, and remediation target date.",
      validating: "Validate exploitability and affected systems.",
      remediating: "Track the corrective work and evidence of closure.",
      accepted: "Document the acceptance rationale and review trigger.",
      resolved: "Verify the fix and close the remaining evidence gap.",
      closed: "Retain the record for audit and trend analysis.",
    },
  }),
  risk_scenarios: createWorkflowBlueprint({
    objective: "Build full asset-threat-vulnerability scenarios and move them through treatment, acceptance, or closure.",
    contextFields: ["risk_level", "related_infrastructure_name", "scenario_owner"],
    ownerFields: ["scenario_owner"],
    dueFields: ["review_due_date"],
    blockerRules: [
      { when: (row) => !row.scenario_summary, label: "Scenario summary missing" },
      { when: (row) => ["high", "critical"].includes(row.risk_level) && !row.response_plan, label: "Response plan missing for a high-priority scenario" },
    ],
    stageNotes: {
      identified: "The scenario is captured and needs full assessment.",
      assessing: "Likelihood, impact, and treatment options are being refined.",
      mitigating: "Mitigation work is underway for this scenario.",
      accepted: "Residual exposure was formally accepted.",
      closed: "Treatment is complete and the scenario is closed.",
    },
    nextActionLabels: {
      identified: "Link the scenario to the right asset, threat, and vulnerability.",
      assessing: "Validate score, impact narrative, and owner.",
      mitigating: "Track the treatment actions and due review date.",
      accepted: "Retain the acceptance rationale and next review trigger.",
      closed: "Keep the scenario as reference evidence for future reviews.",
    },
  }),
  risk_assessment_reviews: createWorkflowBlueprint({
    objective: "Run structured review cycles for risk scenarios and register entries, with a visible decision and follow-up date.",
    contextFields: ["decision", "residual_risk_level", "risk_scenario_title"],
    ownerFields: ["reviewer_stakeholder_name"],
    dueFields: ["review_date", "follow_up_date"],
    blockerRules: [
      { when: (row) => !row.summary, label: "Review summary missing" },
      { when: (row) => !row.recommendations, label: "Recommendations missing" },
    ],
    nextActionLabels: {
      planned: "Confirm the review scope, reviewer, and decision criteria.",
      in_review: "Capture the review reasoning, decision, and recommendations.",
      validated: "Use the validated review as the current decision baseline.",
      completed: "Track the follow-up date and linked treatment actions.",
    },
  }),
  threat_bulletins: createWorkflowBlueprint({
    objective: "Prepare, validate, and circulate threat bulletins with a clear validity window and recommended actions.",
    contextFields: ["bulletin_type", "severity", "target_sector"],
    dueFields: ["issued_on", "valid_until"],
    blockerRules: [
      { when: (row) => !row.summary, label: "Bulletin summary missing" },
      { when: (row) => !row.recommended_actions, label: "Recommended actions missing" },
    ],
    nextActionLabels: {
      draft: "Prepare the bulletin text and confirm the target audience.",
      submitted: "Route the bulletin for review and release approval.",
      validated: "Treat this as approved for operational circulation.",
      active: "Monitor validity and update or archive it on time.",
      archived: "Retain the bulletin for institutional memory only.",
    },
  }),
  indicators: createWorkflowBlueprint({
    objective: "Keep indicators of compromise usable, current, and aligned with bulletins or threat events.",
    contextFields: ["indicator_type", "value", "related_bulletin_title"],
    dueFields: ["first_seen_at", "last_seen_at"],
    blockerRules: [
      { when: (row) => !row.value, label: "Indicator value missing" },
      { when: (row) => row.status === "expired", label: "Indicator already expired" },
    ],
    stageNotes: {
      new: "The indicator was just added and needs validation or sharing.",
      active: "The indicator is live and can be used operationally.",
      monitoring: "The indicator remains under watch for new sightings.",
      expired: "The indicator is no longer operationally valid.",
      revoked: "The indicator was revoked and should not be used further.",
    },
    nextActionLabels: {
      new: "Confirm the source and scope before wider use.",
      active: "Use the indicator in monitoring and sharing workflows.",
      monitoring: "Keep the last-seen timestamp and context current.",
      expired: "Replace or refresh the indicator if it remains relevant.",
      revoked: "Retain the record for history but stop operational use.",
    },
  }),
  distribution_groups: createWorkflowBlueprint({
    objective: "Maintain reusable sectoral and institutional groups for structured information sharing.",
    contextFields: ["group_type", "target_sector"],
    blockerRules: [
      { when: (row) => !row.title, label: "Group title missing" },
    ],
    nextActionLabels: {
      draft: "Define the group scope and add the first target members.",
      active: "Keep membership and target sector current.",
      in_review: "Validate whether this group still fits the operating model.",
      archived: "Keep the group only for historical traceability.",
    },
  }),
  information_shares: createWorkflowBlueprint({
    objective: "Track how threat bulletins and alerts are distributed, acknowledged, and followed up.",
    contextFields: ["share_channel", "distribution_group_title", "target_stakeholder_name"],
    dueFields: ["shared_at", "acknowledgement_due_date"],
    blockerRules: [
      { when: (row) => !row.distribution_group_title && !row.target_stakeholder_name, label: "No target audience selected" },
      { when: (row) => ["shared", "acknowledged"].includes(row.status) && !row.shared_at, label: "Share time missing" },
      { when: (row) => !row.message_summary, label: "Message summary missing" },
    ],
    stageNotes: {
      draft: "The message is being prepared and not yet ready to send.",
      prepared: "Content is ready and waiting for release.",
      shared: "The message was sent and should now be acknowledged.",
      acknowledged: "The target audience responded and follow-up can close out.",
      closed: "The sharing cycle is complete and retained for traceability.",
    },
    nextActionLabels: {
      draft: "Define the audience, channel, and message summary.",
      prepared: "Set the share time and acknowledgement due date.",
      shared: "Track acknowledgements and any requested actions.",
      acknowledged: "Capture the response and close remaining follow-up work.",
      closed: "Retain the distribution evidence and final response note.",
    },
  }),
  acknowledgements: createWorkflowBlueprint({
    objective: "Record which institutions received, actioned, or declined a shared alert or bulletin.",
    contextFields: ["information_share_title", "stakeholder_name"],
    dueFields: ["responded_at"],
    blockerRules: [
      { when: (row) => !row.stakeholder_name, label: "Stakeholder missing" },
    ],
    stageNotes: {
      pending: "A response is still expected from the target stakeholder.",
      received: "Receipt was confirmed and follow-up may still continue.",
      actioned: "The stakeholder acted on the request or advice.",
      declined: "The stakeholder declined or could not act as requested.",
    },
    nextActionLabels: {
      pending: "Follow up for acknowledgement or action evidence.",
      received: "Decide whether any extra action is still needed.",
      actioned: "Retain the evidence of action and close the loop.",
      declined: "Record the reason and decide whether to escalate.",
    },
  }),
  generated_documents: createWorkflowBlueprint({
    objective: "Generate, review, approve, and archive formal platform outputs with clear version tracking.",
    contextFields: ["module_label", "document_type", "version_label"],
    ownerFields: ["generated_by_name", "approved_by_name"],
    dueFields: ["generated_on", "published_on"],
    blockerRules: [
      { when: (row) => !row.content_text, label: "Document content missing" },
      { when: (row) => row.status === "in_review" && !row.summary, label: "Review summary missing" },
    ],
    stageNotes: {
      generated: "The document snapshot is ready and awaiting formal review.",
      in_review: "The document is under review and may still require updates.",
      approved: "The document is approved and can be used as controlled output.",
      superseded: "A newer version replaced this document.",
      archived: "The document is retained for traceability only.",
    },
    nextActionLabels: {
      generated: "Assign a reviewer and capture any approval conditions.",
      in_review: "Record the requested changes or approve the current version.",
      approved: "Retain this version as the approved baseline output.",
      superseded: "Reference the newer approved version where needed.",
      archived: "Keep this document for audit trail and presentation history.",
    },
  }),
  review_cycles: createWorkflowBlueprint({
    objective: "Keep recurring reviews scheduled, overdue items visible, and the current approved version easy to trace.",
    contextFields: ["module_label", "record_title", "current_version_label"],
    ownerFields: ["owner_name"],
    dueFields: ["last_review_date", "next_review_date"],
    blockerRules: [
      { when: (row) => !row.next_review_date && row.status !== "completed", label: "Next review date missing" },
      { when: (row) => !row.current_version_label, label: "Current version not recorded" },
    ],
    stageNotes: {
      draft: "The review cadence is being defined and not yet operational.",
      active: "The review cycle is live and should be kept current.",
      overdue: "The review date passed and follow-up is now required.",
      completed: "The review cycle closed for this planned round.",
      archived: "The cycle is no longer active and is kept for history.",
    },
    nextActionLabels: {
      draft: "Confirm scope, owner, and the next review date.",
      active: "Monitor the due date and prepare the next review package.",
      overdue: "Schedule or complete the delayed review immediately.",
      completed: "Open the next cycle only if another review round is needed.",
      archived: "Keep the cycle for traceability and version history.",
    },
  }),
  review_records: createWorkflowBlueprint({
    objective: "Capture formal review decisions, requested changes, and the next review commitment for each controlled output.",
    contextFields: ["review_cycle_title", "generated_document_title", "version_label"],
    ownerFields: ["reviewer_name"],
    dueFields: ["review_date", "next_review_date"],
    blockerRules: [
      { when: (row) => !row.reviewer_name, label: "Reviewer missing" },
      { when: (row) => row.decision === "changes_requested" && !row.recommendations, label: "Requested changes not documented" },
    ],
    nextActionLabels: {
      draft: "Prepare the decision note and the reviewer details.",
      in_review: "Capture recommendations and confirm the final decision.",
      completed: "Keep the decision as formal review evidence.",
      archived: "Retain the record only for the audit trail.",
    },
  }),
  capacity_assessments: createWorkflowBlueprint({
    objective: "Measure preparedness, document gaps, and convert them into targeted strengthening actions.",
    contextFields: ["assessment_area", "gap_level", "scope"],
    ownerFields: ["lead_assessor", "stakeholder_name"],
    dueFields: ["due_date", "completed_date"],
    blockerRules: [
      { when: (row) => row.current_maturity === null || row.current_maturity === undefined, label: "Current maturity score missing" },
      { when: (row) => row.target_maturity === null || row.target_maturity === undefined, label: "Target maturity score missing" },
      { when: (row) => ["high", "critical"].includes(row.gap_level) && !row.priority_actions, label: "Priority actions not defined for a major gap" },
    ],
    nextActionLabels: {
      draft: "Define the assessment scope and method.",
      planned: "Confirm the assessors, dates, and evidence sources.",
      in_progress: "Capture baseline findings and gap levels.",
      in_review: "Validate the gap narrative and action priorities.",
      validated: "Turn approved actions into monitored tasks.",
      completed: "Use the baseline for the next readiness review.",
    },
  }),
  contingency_plans: createWorkflowBlueprint({
    objective: "Develop, validate, and operationalize contingency procedures and coordination steps.",
    contextFields: ["plan_type", "scope", "review_cycle"],
    dueFields: ["next_review_date"],
    blockerRules: [
      { when: (row) => !row.communication_procedure, label: "Communication procedure missing" },
      { when: (row) => !row.coordination_mechanism, label: "Coordination mechanism missing" },
    ],
    nextActionLabels: {
      draft: "Complete the plan structure and activation logic.",
      planned: "Prepare internal review and stakeholder walkthroughs.",
      in_review: "Resolve comments on activation, comms, and coordination.",
      validated: "Publish the plan and communicate the operating model.",
      active: "Keep the review cycle and supporting assets current.",
      completed: "Archive only after a replacement plan is in place.",
    },
  }),
  emergency_response_assets: createWorkflowBlueprint({
    objective: "Keep emergency assets visible, assigned, and ready for activation.",
    contextFields: ["asset_type", "priority", "location"],
    ownerFields: ["owner_stakeholder_name", "owner_name"],
    blockerRules: [
      { when: (row) => row.availability_status === "constrained", label: "Asset is constrained" },
      { when: (row) => row.availability_status === "unavailable", label: "Asset is unavailable" },
    ],
    stageNotes: {
      planned: "Asset is expected but not yet ready.",
      ready: "Asset can be activated.",
      constrained: "Asset is only partly usable.",
      unavailable: "Asset needs recovery or replacement.",
    },
    nextActionLabels: {
      planned: "Confirm ownership, location, and activation notes.",
      ready: "Keep the readiness assumptions current.",
      constrained: "Log the constraint and define a workaround.",
      unavailable: "Escalate the gap and assign restoration actions.",
    },
  }),
  simulation_exercises: createWorkflowBlueprint({
    objective: "Plan, run, and close simulations with findings and lessons learned that feed back into the programme.",
    contextFields: ["exercise_type", "contingency_plan_title", "participating_sectors"],
    dueFields: ["planned_date", "completed_date"],
    blockerRules: [
      { when: (row) => !row.scenario, label: "Exercise scenario missing" },
      { when: (row) => row.status === "completed" && !row.lessons_learned, label: "Lessons learned not captured" },
    ],
    nextActionLabels: {
      planned: "Confirm the scenario, participants, and exercise date.",
      in_progress: "Capture findings and coordination issues during execution.",
      completed: "Turn findings into actions and update related plans.",
    },
  }),
  cyber_standards: createWorkflowBlueprint({
    objective: "Move standards from drafting to validated adoption and recurring review.",
    contextFields: ["standard_type", "target_sector", "version"],
    ownerFields: ["owner_name"],
    dueFields: ["next_review_date"],
    blockerRules: [
      { when: (row) => !row.control_focus, label: "Control focus missing" },
      { when: (row) => !row.summary, label: "Standard summary missing" },
    ],
    nextActionLabels: {
      draft: "Complete the control baseline and target scope.",
      planned: "Prepare consultation and pilot adoption steps.",
      in_review: "Incorporate technical and regulatory feedback.",
      validated: "Publish the validated version and adoption notes.",
      active: "Track implementation and keep the review cycle current.",
    },
  }),
  audit_frameworks: createWorkflowBlueprint({
    objective: "Establish audit methods, response checks, and review cycles that can be run consistently.",
    contextFields: ["scope", "audit_frequency", "related_standard_title"],
    dueFields: ["next_review_date"],
    blockerRules: [
      { when: (row) => !row.incident_response_procedure, label: "Incident response procedure missing" },
      { when: (row) => !row.recovery_procedure, label: "Recovery procedure missing" },
    ],
    nextActionLabels: {
      draft: "Define the audit scope and method.",
      planned: "Confirm review cadence and required evidence.",
      submitted: "Route the framework for validation.",
      validated: "Publish the approved framework and rollout plan.",
      active: "Use the framework and keep review notes current.",
    },
  }),
  standard_requirements: createWorkflowBlueprint({
    objective: "Break each standard into named requirements that can be implemented, reviewed, and audited consistently.",
    contextFields: ["related_standard_title", "requirement_type", "chapter"],
    ownerFields: ["owner_name"],
    blockerRules: [
      { when: (row) => !row.implementation_guidance, label: "Implementation guidance missing" },
      { when: (row) => !row.verification_method, label: "Verification method missing" },
    ],
    nextActionLabels: {
      draft: "Define the requirement scope and implementation guidance.",
      planned: "Confirm ownership and rollout priority.",
      in_review: "Validate the wording with implementation and audit leads.",
      validated: "Publish the approved requirement baseline.",
      active: "Use the requirement in assessments and audits.",
    },
  }),
  standard_controls: createWorkflowBlueprint({
    objective: "Translate each requirement into controls with a clear objective, method, and measurement path.",
    contextFields: ["related_standard_title", "domain", "control_type"],
    ownerFields: ["owner_name"],
    blockerRules: [
      { when: (row) => !row.control_objective, label: "Control objective missing" },
      { when: (row) => !row.measurement_criteria, label: "Measurement criteria missing" },
    ],
    nextActionLabels: {
      draft: "Define the control objective and operating method.",
      planned: "Confirm the owner and expected evidence trail.",
      in_review: "Review feasibility and auditability with the programme team.",
      validated: "Adopt the control into assessments and audits.",
      active: "Track implementation and update the control when standards evolve.",
    },
  }),
  conformity_assessments: createWorkflowBlueprint({
    objective: "Assess conformity requirement by requirement and turn evidence gaps into tracked remediation work.",
    contextFields: ["related_standard_title", "related_control_title", "conformity_level"],
    ownerFields: ["assessor_name", "target_stakeholder_name"],
    dueFields: ["assessed_on", "next_review_date"],
    blockerRules: [
      { when: (row) => !row.evidence_summary, label: "Evidence summary missing" },
      { when: (row) => row.conformity_level === "non_conformant" && !row.gap_summary, label: "Gap summary missing for a non-conformant result" },
      { when: (row) => row.conformity_level === "non_conformant" && !row.follow_up_action, label: "Follow-up action missing for a non-conformant result" },
    ],
    nextActionLabels: {
      planned: "Define the scope, assessor, and target review date.",
      in_review: "Validate evidence and confirm the conformity rating.",
      validated: "Use the validated result as the reference assessment baseline.",
      completed: "Retain the assessment and monitor follow-up actions.",
    },
  }),
  control_evidence: createWorkflowBlueprint({
    objective: "Track evidence quality, validity, and review status for standards and audit checks.",
    contextFields: ["related_standard_title", "related_control_title", "evidence_type"],
    ownerFields: ["owner_name"],
    dueFields: ["captured_on", "validity_until"],
    blockerRules: [
      { when: (row) => !row.reference_url && !row.reference_label, label: "Evidence reference missing" },
      { when: (row) => row.status === "expired", label: "Evidence validity already expired" },
    ],
    nextActionLabels: {
      pending: "Collect the evidence and attach a usable reference.",
      available: "Review the evidence against the expected control outcome.",
      reviewed: "Keep the evidence current until the next audit or review.",
      rejected: "Replace the rejected evidence with a stronger artefact.",
      expired: "Refresh or replace the expired evidence item.",
    },
  }),
  audit_plans: createWorkflowBlueprint({
    objective: "Schedule and run audits with a clear scope, time window, lead auditor, and next step.",
    contextFields: ["related_framework_title", "related_standard_title", "scope"],
    ownerFields: ["lead_auditor", "target_stakeholder_name"],
    dueFields: ["planned_start_date", "planned_end_date", "actual_end_date"],
    blockerRules: [
      { when: (row) => !row.planned_start_date, label: "Planned start date missing" },
      { when: (row) => !row.planned_end_date, label: "Planned end date missing" },
      { when: (row) => !row.objectives, label: "Audit objectives missing" },
    ],
    nextActionLabels: {
      draft: "Define the scope, audit lead, and target dates.",
      planned: "Confirm the sampling strategy and expected evidence set.",
      in_progress: "Run the audit, update checklist progress, and log findings quickly.",
      in_review: "Validate the findings and close evidence gaps.",
      completed: "Keep the audit package as reference evidence and follow-up input.",
    },
  }),
  audit_checklists: createWorkflowBlueprint({
    objective: "Execute audit checks step by step and capture a result plus evidence for each control point.",
    contextFields: ["audit_plan_title", "related_control_title", "result"],
    dueFields: [],
    blockerRules: [
      { when: (row) => row.status === "blocked", label: "Checklist item is blocked" },
      { when: (row) => row.status === "completed" && !row.result, label: "Completed item missing a result" },
      { when: (row) => row.status === "completed" && !row.evidence_reference && !row.finding_summary, label: "Completed item missing evidence or finding summary" },
    ],
    nextActionLabels: {
      planned: "Prepare the verification step and expected evidence.",
      in_progress: "Capture the result and attach supporting evidence.",
      blocked: "Resolve the blocker or escalate it to the audit lead.",
      completed: "Retain the result as the audit execution record.",
      skipped: "Explain why the item was skipped and whether follow-up is needed.",
    },
  }),
  audit_findings: createWorkflowBlueprint({
    objective: "Track findings from identification to validated remediation and closure.",
    contextFields: ["audit_plan_title", "severity", "related_control_title"],
    ownerFields: ["owner_name"],
    dueFields: ["due_date"],
    blockerRules: [
      { when: (row) => !row.recommendation, label: "Recommendation missing" },
      { when: (row) => !row.owner_name && row.status !== "closed", label: "Owner missing" },
    ],
    nextActionLabels: {
      identified: "Validate the finding, owner, and remediation expectation.",
      in_review: "Confirm severity, impact, and closure criteria.",
      validated: "Launch remediation and tie it to corrective actions.",
      remediating: "Track remediation progress and supporting evidence.",
      resolved: "Verify the resolution before final closure.",
      closed: "Retain the finding and closure evidence for traceability.",
    },
  }),
  non_conformities: createWorkflowBlueprint({
    objective: "Manage non-conformities from opening through remediation and verified closure.",
    contextFields: ["audit_finding_title", "severity", "related_control_title"],
    ownerFields: ["owner_name"],
    dueFields: ["due_date"],
    blockerRules: [
      { when: (row) => !row.root_cause && row.status !== "open", label: "Root cause still missing" },
      { when: (row) => !row.remediation_expectation && row.status !== "open", label: "Remediation expectation missing" },
    ],
    nextActionLabels: {
      open: "Confirm the issue statement, owner, and remediation expectation.",
      in_review: "Validate the root cause and containment action.",
      accepted: "Record the acceptance rationale and next review date.",
      remediating: "Track the remediation effort and evidence of progress.",
      resolved: "Verify the fix before closing the non-conformity.",
      closed: "Retain the closure record for audit traceability.",
    },
  }),
  corrective_actions: createWorkflowBlueprint({
    objective: "Turn findings and non-conformities into accountable remediation actions with clear deadlines and evidence.",
    contextFields: ["related_finding_title", "related_non_conformity_title", "related_infrastructure_name"],
    ownerFields: ["owner_name"],
    dueFields: ["start_date", "due_date", "completed_date"],
    blockerRules: [
      { when: (row) => !row.owner_name, label: "Owner missing" },
      { when: (row) => Boolean(row.blocker_summary), label: (row) => row.blocker_summary || "Corrective action is blocked" },
      { when: (row) => !row.action_summary, label: "Action summary missing" },
    ],
    nextActionLabels: {
      planned: "Confirm the owner, action scope, and delivery timeline.",
      in_progress: "Track remediation progress and escalate blockers early.",
      in_review: "Validate closure evidence and the success metric.",
      completed: "Keep the corrective action linked to the resolved finding.",
      archived: "Retain the record as historical remediation evidence.",
    },
  }),
  training_programs: createWorkflowBlueprint({
    objective: "Take training programmes from design to completed delivery with clear target audience and participation goals.",
    contextFields: ["program_type", "delivery_mode", "target_audience"],
    dueFields: [],
    blockerRules: [
      { when: (row) => !row.participant_target, label: "Participant target missing" },
      { when: (row) => !row.summary, label: "Training summary missing" },
    ],
    nextActionLabels: {
      planned: "Confirm the delivery format, audience, and logistics.",
      in_progress: "Track attendance and the active delivery status.",
      completed: "Capture completion evidence and outputs.",
    },
  }),
  deliverable_milestones: createWorkflowBlueprint({
    objective: "Monitor programme outputs against phase, due date, and validation status.",
    contextFields: ["phase", "deliverable_category", "planned_week"],
    ownerFields: ["owner_name"],
    dueFields: ["due_date"],
    blockerRules: [
      { when: (row) => !row.owner_name, label: "Owner missing" },
      { when: (row) => !row.due_date, label: "Due date missing" },
    ],
    nextActionLabels: {
      draft: "Define the deliverable scope and accountable owner.",
      planned: "Confirm the production window and due date.",
      in_progress: "Track delivery effort and dependencies.",
      validated: "Retain sign-off and handover details.",
      completed: "Keep this milestone as completed evidence.",
    },
  }),
  action_plan_tasks: createWorkflowBlueprint({
    objective: "Turn gaps and decisions into accountable action items with blockers and next steps made visible.",
    contextFields: ["workstream", "priority", "related_infrastructure_name"],
    ownerFields: ["owner_name"],
    dueFields: ["due_date", "completed_date"],
    blockerRules: [
      { when: (row) => !row.owner_name, label: "Owner missing" },
      { when: (row) => Boolean(row.blocker_summary), label: (row) => row.blocker_summary || "Task is blocked" },
      { when: (row) => !row.next_step && row.status !== "completed", label: "Next step not defined" },
    ],
    nextActionLabels: {
      draft: "Clarify the task scope and success metric.",
      planned: "Confirm the owner, start date, and first step.",
      in_progress: "Update progress and escalate blockers early.",
      in_review: "Validate completion evidence before closing.",
      completed: "Keep this task linked to the related gap or deliverable.",
    },
  }),
  sop_templates: createWorkflowBlueprint({
    objective: "Keep executable SOP templates ready, reviewed, and linked to the plans and assets they operationalize.",
    contextFields: ["code", "version", "contingency_plan_title"],
    ownerFields: ["owner_stakeholder_name"],
    dueFields: ["last_reviewed_at"],
    blockerRules: [
      { when: (row) => !row.activation_trigger, label: "Activation trigger missing" },
      { when: (row) => !row.objective, label: "Operational objective missing" },
      { when: (row) => !row.step_count, label: "No SOP steps configured yet" },
    ],
    nextActionLabels: {
      draft: "Finish the objective, trigger, and checklist structure.",
      ready: "Validate the step set and confirm the template can be launched.",
      active: "Keep the template aligned with current plans and infrastructure.",
      archived: "Retain for traceability only if a newer template replaced it.",
    },
  }),
  sop_executions: createWorkflowBlueprint({
    objective: "Execute operational SOPs step by step with live blockers, timing, and completion progress.",
    contextFields: ["incident_title", "template_title", "execution_commander_name"],
    ownerFields: ["execution_commander_name"],
    dueFields: ["target_completion_at", "completed_at"],
    blockerRules: [
      { when: (row) => row.status === "blocked" || Boolean(row.blocker_summary), label: (row) => row.blocker_summary || "Execution is blocked" },
      { when: (row) => !row.template_title, label: "No linked template" },
    ],
    stageNotes: {
      planned: "The execution is prepared but not yet started.",
      active: "The runbook is live and steps should be updated continuously.",
      blocked: "Execution hit a blocker that needs operational support.",
      completed: "The SOP run finished and should keep outcomes and evidence.",
      cancelled: "The run was stopped and remains for traceability.",
    },
    nextActionLabels: {
      planned: "Start the execution and assign the first active steps.",
      active: "Advance the checklist, capture evidence, and clear blockers early.",
      blocked: "Resolve the blocker or escalate it to incident leadership.",
      completed: "Close out outcomes, evidence, and lessons learned.",
      cancelled: "Document why the execution was cancelled.",
    },
  }),
  asset_allocations: createWorkflowBlueprint({
    objective: "Move emergency assets from request through mobilization, deployment, and release with clear destination context.",
    contextFields: ["incident_title", "emergency_asset_name", "destination_infrastructure_name"],
    ownerFields: ["requested_by_name", "approved_by_name"],
    dueFields: ["requested_at", "deployed_at", "released_at"],
    blockerRules: [
      { when: (row) => row.asset_availability_status === "unavailable", label: "Requested asset is unavailable" },
      { when: (row) => row.asset_availability_status === "constrained", label: "Requested asset is constrained" },
      { when: (row) => !row.destination && !row.destination_infrastructure_name, label: "No deployment destination defined" },
    ],
    stageNotes: {
      requested: "The allocation is waiting for operational approval.",
      approved: "The allocation is approved and should move into mobilization.",
      mobilizing: "The asset is preparing to move into the field or live response.",
      deployed: "The asset is active on the incident and should be monitored.",
      demobilizing: "The asset is coming off the incident and winding down.",
      released: "The asset is released and should return to readiness tracking.",
      cancelled: "The allocation was cancelled and remains for traceability.",
    },
    nextActionLabels: {
      requested: "Confirm the quantity, approver, and destination.",
      approved: "Mobilize the asset and record the deployment time.",
      mobilizing: "Track movement, arrival, and operational readiness.",
      deployed: "Capture deployment notes and prepare the release plan.",
      demobilizing: "Record return timing and any release notes.",
      released: "Return the asset to readiness or maintenance workflow.",
      cancelled: "Document why this allocation was cancelled.",
    },
  }),
  incidents: createWorkflowBlueprint({
    objective: "Run incident coordination from first report through containment, recovery, and closure with clear operational ownership.",
    contextFields: ["incident_type", "severity", "lead_stakeholder_name"],
    ownerFields: ["incident_coordinator_name"],
    dueFields: ["next_update_due", "containment_target_at", "recovery_target_at"],
    blockerRules: [
      { when: (row) => ["critical", "national"].includes(row.severity) && !row.incident_coordinator_name, label: "Coordinator missing for a severe incident" },
      { when: (row) => ["active", "contained", "recovering"].includes(row.status) && (!Array.isArray(row.affected_infrastructure_names) || row.affected_infrastructure_names.length === 0), label: "Affected infrastructure not linked" },
      { when: (row) => ["high", "critical", "national"].includes(row.severity) && !row.linked_plan_title, label: "No linked contingency plan" },
    ],
    stageNotes: {
      reported: "The incident is logged and waiting for the first operational triage.",
      assessing: "Scope, impact, and ownership are being confirmed.",
      active: "Response actions are underway and updates should stay frequent.",
      contained: "Immediate spread is under control, but stabilization continues.",
      recovering: "Services are being restored and residual risk is being monitored.",
      closed: "The incident is closed and should retain lessons learned and evidence.",
    },
    nextActionLabels: {
      reported: "Confirm severity, coordinator, and the first situation update.",
      assessing: "Validate affected sectors, infrastructure, and the linked contingency plan.",
      active: "Track response tasks, assignments, and outbound communications.",
      contained: "Prepare recovery actions and the next command update.",
      recovering: "Confirm restoration progress and capture residual issues.",
      closed: "Lock in lessons learned, evidence, and the final decision log.",
    },
  }),
  incident_tasks: createWorkflowBlueprint({
    objective: "Turn incident decisions into accountable operational tasks with ownership, deadlines, and blockers made visible.",
    contextFields: ["incident_title", "priority", "assigned_to_name"],
    ownerFields: ["assigned_to_name"],
    dueFields: ["due_at", "completed_at"],
    blockerRules: [
      { when: (row) => !row.assigned_to_name && row.status !== "completed", label: "Task owner missing" },
      { when: (row) => row.status === "blocked" || Boolean(row.blocker_summary), label: (row) => row.blocker_summary || "Task is blocked" },
    ],
    stageNotes: {
      planned: "The task is defined and waiting for execution to begin.",
      in_progress: "The task is active and should carry current progress notes.",
      blocked: "Execution is blocked and needs coordination help.",
      completed: "The task finished and should keep closure evidence.",
      cancelled: "The task was cancelled and remains only for traceability.",
    },
    nextActionLabels: {
      planned: "Confirm the owner, due time, and first execution step.",
      in_progress: "Keep the next step and risk of slippage visible.",
      blocked: "Remove the blocker or escalate it to incident leadership.",
      completed: "Retain the completion evidence and outcome note.",
      cancelled: "Document why the task was cancelled.",
    },
  }),
};

const MODULE_BEHAVIORS = {
  sop_templates: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.sop_templates,
    reportPreset: "review",
    viewLabels: { workflow: "Template workflow", report: "Template report" },
  },
  sop_executions: {
    extraViews: ["workflow", "execute", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.sop_executions,
    reportPreset: "sop-execution",
    viewLabels: { workflow: "Execution workflow", execute: "Execution workspace", report: "Execution report" },
  },
  asset_allocations: {
    extraViews: ["workflow", "map", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.asset_allocations,
    reportPreset: "allocation",
    viewLabels: { workflow: "Allocation board", map: "Allocation map", report: "Allocation report" },
  },
  incidents: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.incidents,
    reportPreset: "incident",
    viewLabels: { workflow: "Incident workflow", report: "Incident report" },
  },
  incident_tasks: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.incident_tasks,
    reportPreset: "incident-task",
    viewLabels: { workflow: "Task workflow", report: "Task report" },
  },
  cybergrc_stakeholders: {
    extraViews: ["workflow"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.cybergrc_stakeholders,
    viewLabels: { workflow: "Engagement workflow" },
    formPresentation: STAKEHOLDER_FORM_PRESENTATION,
  },
  critical_infrastructure: {
    extraViews: ["workflow", "map", "report"],
    workflowField: "mapping_status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.critical_infrastructure,
    reportPreset: "mapping",
    viewLabels: { workflow: "Mapping workflow", map: "GIS map", report: "Coverage report" },
  },
  governance_artifacts: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.governance_artifacts,
    reportPreset: "review",
    viewLabels: { workflow: "Validation workflow", report: "Review report" },
  },
  desk_study_reviews: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.desk_study_reviews,
    reportPreset: "desk-study",
    viewLabels: { workflow: "Desk study workflow", report: "Desk study report" },
  },
  stakeholder_consultations: {
    extraViews: ["workflow", "report", "calendar"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.stakeholder_consultations,
    reportPreset: "consultation",
    viewLabels: { workflow: "Consultation workflow", report: "Consultation report", calendar: "Meeting calendar" },
    formPresentation: CONSULTATION_FORM_PRESENTATION,
  },
  risk_register_entries: {
    extraViews: ["workflow", "report"],
    workflowField: "treatment_status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.risk_register_entries,
    reportPreset: "risk",
    viewLabels: { workflow: "Treatment workflow", report: "Risk report" },
  },
  asset_inventory_items: {
    extraViews: ["workflow", "map", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.asset_inventory_items,
    reportPreset: "asset-inventory",
    viewLabels: { workflow: "Inventory workflow", map: "GIS map", report: "Inventory report" },
  },
  threat_events: {
    extraViews: ["workflow", "map", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.threat_events,
    reportPreset: "threat",
    viewLabels: { workflow: "Threat workflow", map: "Threat map", report: "Threat report" },
  },
  vulnerability_records: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.vulnerability_records,
    reportPreset: "vulnerability",
    viewLabels: { workflow: "Vulnerability workflow", report: "Vulnerability report" },
  },
  risk_scenarios: {
    extraViews: ["workflow", "report"],
    workflowField: "treatment_status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.risk_scenarios,
    reportPreset: "risk-scenario",
    viewLabels: { workflow: "Scenario workflow", report: "Scenario report" },
  },
  risk_assessment_reviews: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.risk_assessment_reviews,
    reportPreset: "risk-review",
    viewLabels: { workflow: "Review workflow", report: "Review report" },
  },
  threat_bulletins: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.threat_bulletins,
    reportPreset: "bulletin",
    viewLabels: { workflow: "Bulletin workflow", report: "Bulletin report" },
  },
  indicators: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.indicators,
    reportPreset: "indicator",
    viewLabels: { workflow: "Indicator workflow", report: "Indicator report" },
  },
  distribution_groups: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.distribution_groups,
    reportPreset: "distribution-group",
    viewLabels: { workflow: "Group workflow", report: "Group report" },
  },
  information_shares: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.information_shares,
    reportPreset: "information-share",
    viewLabels: { workflow: "Sharing workflow", report: "Sharing report" },
  },
  acknowledgements: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.acknowledgements,
    reportPreset: "acknowledgement",
    viewLabels: { workflow: "Acknowledgement workflow", report: "Acknowledgement report" },
  },
  generated_documents: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.generated_documents,
    reportPreset: "generated-document",
    viewLabels: { workflow: "Document workflow", report: "Document library" },
  },
  review_cycles: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.review_cycles,
    reportPreset: "review-cycle",
    viewLabels: { workflow: "Review cycle workflow", report: "Review cycle report" },
  },
  review_records: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.review_records,
    reportPreset: "review-record",
    viewLabels: { workflow: "Review workflow", report: "Review record report" },
  },
  change_log_entries: {
    extraViews: ["report"],
    reportPreset: "change-log",
    viewLabels: { report: "Change log report" },
  },
  capacity_assessments: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.capacity_assessments,
    reportPreset: "capacity",
    viewLabels: { workflow: "Capacity workflow", report: "Capacity report" },
  },
  contingency_plans: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.contingency_plans,
    reportPreset: "review",
    viewLabels: { workflow: "Activation workflow", report: "Review report" },
  },
  emergency_response_assets: {
    extraViews: ["workflow", "map"],
    workflowField: "availability_status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.emergency_response_assets,
    viewLabels: { workflow: "Readiness board", map: "Asset map" },
  },
  simulation_exercises: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.simulation_exercises,
    reportPreset: "exercise",
    viewLabels: { workflow: "Exercise workflow", report: "Exercise report" },
  },
  cyber_standards: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.cyber_standards,
    reportPreset: "review",
    viewLabels: { workflow: "Adoption workflow", report: "Review report" },
  },
  audit_frameworks: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.audit_frameworks,
    reportPreset: "review",
    viewLabels: { workflow: "Audit workflow", report: "Review report" },
  },
  standard_requirements: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.standard_requirements,
    reportPreset: "review",
    viewLabels: { workflow: "Requirement workflow", report: "Requirement report" },
  },
  standard_controls: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.standard_controls,
    reportPreset: "review",
    viewLabels: { workflow: "Control workflow", report: "Control report" },
  },
  conformity_assessments: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.conformity_assessments,
    reportPreset: "conformity",
    viewLabels: { workflow: "Assessment workflow", report: "Conformity report" },
  },
  control_evidence: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.control_evidence,
    reportPreset: "evidence",
    viewLabels: { workflow: "Evidence workflow", report: "Evidence report" },
  },
  audit_plans: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.audit_plans,
    reportPreset: "audit-plan",
    viewLabels: { workflow: "Audit plan workflow", report: "Audit plan report" },
  },
  audit_checklists: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.audit_checklists,
    reportPreset: "audit-checklist",
    viewLabels: { workflow: "Checklist workflow", report: "Checklist report" },
  },
  audit_findings: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.audit_findings,
    reportPreset: "finding",
    viewLabels: { workflow: "Finding workflow", report: "Finding report" },
  },
  non_conformities: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.non_conformities,
    reportPreset: "non-conformity",
    viewLabels: { workflow: "Non-conformity workflow", report: "Non-conformity report" },
  },
  corrective_actions: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.corrective_actions,
    reportPreset: "corrective-action",
    viewLabels: { workflow: "Corrective workflow", report: "Corrective action report" },
  },
  training_programs: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.training_programs,
    reportPreset: "training",
    viewLabels: { workflow: "Delivery workflow", report: "Training report" },
  },
  deliverable_milestones: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.deliverable_milestones,
    reportPreset: "delivery",
    viewLabels: { workflow: "Delivery workflow", report: "Delivery report" },
  },
  action_plan_tasks: {
    extraViews: ["workflow", "report"],
    workflowField: "status",
    workflowBlueprint: WORKFLOW_BLUEPRINTS.action_plan_tasks,
    reportPreset: "action-plan",
    viewLabels: { workflow: "Action plan workflow", report: "Action plan report" },
  },
};

export function getModuleBehavior(moduleConfigOrKey) {
  const key = typeof moduleConfigOrKey === "string" ? moduleConfigOrKey : moduleConfigOrKey?.key;
  return MODULE_BEHAVIORS[key] || {};
}

export function getSupportedViews(moduleConfig) {
  if (!moduleConfig) return ["list"];

  const behavior = getModuleBehavior(moduleConfig);
  return ["list", ...(moduleConfig.views || []), ...(behavior.extraViews || [])]
    .filter((view, index, values) => values.indexOf(view) === index)
    .filter((view) => view !== "create" || (moduleConfig.formFields || []).length > 0);
}

export function getViewLabel(moduleConfig, view) {
  const behavior = getModuleBehavior(moduleConfig);
  return behavior.viewLabels?.[view] || DEFAULT_VIEW_LABELS[view] || view;
}

export function getFormPresentation(moduleConfig) {
  const behavior = getModuleBehavior(moduleConfig);
  return behavior.formPresentation || null;
}

export function getWorkflowBlueprint(moduleConfig) {
  const behavior = getModuleBehavior(moduleConfig);
  return behavior.workflowBlueprint || null;
}
